version: '3.4'

services:
  notificationservice.application:
    image: notification-service:latest
    build:
      context: .
      dockerfile: Management.Application/Dockerfile
    networks: 
        - my-network
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      networks: 
        - my-network

  mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
          ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
          ME_CONFIG_BASICAUTH_USERNAME: admin
          ME_CONFIG_BASICAUTH_PASSWORD: senha123
        networks:
          - my-network
networks: 
  my-network:
    driver: bridge